### ISSUE TITLE
Unary minus parsing problem

### ISSUE THREAD

**Issue by monadius** [soarlab/gelpia#14]
The following problem is not parsed correctly:

    var:
    [-10, 10] x;

    cost:
    -x^2;

The correct parsing should be `-(x^2)` but it is parsed as `(-x)^2`.

**Comment by keram88** [comment]
Should be working now that Ian gave unary minus lower precedence than infix power.

**Comment by monadius** [comment]
Indeed, everything works now (an example: benchmarks/classical_tests/2d/easom.dop)
