### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by zvonimir** [soarlab/gelpia#25]
A collaborator tried to build Gelpia and he run into the following build error:
```
   Compiling getopts v0.2.18
error[E0301]: cannot mutably borrow in a pattern guard
    --> 
/home/volodya/.cargo/registry/src/github.com-1ecc6299db9ec823/getopts-0.2.18/src/lib.rs:407:73
     |
407 |                         } else if was_long || name_pos < names.len() 
|| args.peek().map_or(true, |n| is_arg(&n)) {
     | 
^^^^ borrowed mutably in pattern guard

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `getopts`.
```

Could someone help us out to get to the bottom of this?

**Comment by zvonimir** [comment]
I guess it might be related to the used version of Rust or something like that.

**Comment by ganeshutah** [comment]
sounds like Rust

Ian is perhaps on (or going to) his honeymoon. His response is bound to be
delayed.

**Comment by IanBriggs** [comment]
Caught me in time for a short break.

Do you know if they are using the bundled dependency builder? It should use
a pinned version of rust.

It’s definitely related to the version of rust. Mark may know for sure if
we pinned the version in the main branch or just one of the other branches.

-Ian

**Comment by zvonimir** [comment]
Thanks Ian!
Yeah, this is almost certainly being done from the master branch. I would guess the person was just following our instructions.
@keram88 is the Rust version pinned in the master branch?
Any other suggestions? Thanks!

**Comment by keram88** [comment]
This is the same issue as this:
https://github.com/soarlab/gelpia/issues/24#issue-367416393

If I remember correctly, the issue has something to do with a compatible version of getopts not being available and requiring some changes in the Python front end. I guess it got lost at ATVA. I'll have to stare at the code again to figure it out and work on a solution with Ian.

**Comment by keram88** [comment]
This has been resolved in the develop branch. We have an upcoming version that uses stable Rust and we are working to reduce dependencies now that the language has matured enough.
