### ISSUE TITLE
Installation takes up >40G

### ISSUE THREAD

**Issue by izycheva** [soarlab/gelpia#33]
Is this normal that the installation of Gelpia takes up more than 40G? 
I checked that the directory `src/func/target/release/deps` alone needs 44G. It has a bunch of files called 'func_generated_*.d'  (the last part of the name varies). Is it safe to remove them after the installation is successfully finished?

**Comment by IanBriggs** [comment]
It is safe to delete these files. They should be cleaned up automatically.

**Comment by izycheva** [comment]
Greta, thanks!
